- logo:
    icon: /images/favicon.ico

- greeting:
    text_size: 4xl
    text: ROGO Home Lab

- greeting:
    text_size: xl
    text:  ğŸ¤–   ğŸ–¥ï¸    ğŸ’¾   ğŸ–²ï¸   âŒ¨ï¸   ğŸ–±ï¸   ğŸ“½ï¸   ğŸ¿   ğŸ“º   ğŸšï¸   ğŸ“»   ğŸ´â€â˜ ï¸   ğŸ¶   ğŸ’½   âï¸   ğŸï¸   ğŸ—’ï¸   ğŸ“²   ğŸ”Œ   ğŸ›ï¸   ğŸª‡

- resources:
    expanded: true
    cpu: true
    cputemp: false
    memory: true
    refresh: 1000

